import { motion, useScroll, useTransform } from 'motion/react';
import { useRef } from 'react';
import { useLanguage } from '../context/LanguageContext';
import SEO from '../components/SEO';

export default function Vision() {
  const containerRef = useRef<HTMLDivElement>(null);
  const { t } = useLanguage();
  
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ['start end', 'end start']
  });

  const y = useTransform(scrollYProgress, [0, 1], [100, -100]);
  const opacity = useTransform(scrollYProgress, [0, 0.2, 0.8, 1], [0, 1, 1, 0]);

  return (
    <motion.main
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 1 }}
      className="bg-[#050505] min-h-[100dvh] text-white pt-32 pb-32 px-8 md:px-16 lg:px-24"
      ref={containerRef}
    >
      <SEO 
        title="Wizja | Luźno Agency - Przyszłość Marketingu i AI"
        description="Poznaj wizję Luźno Agency. Wierzymy w połączenie kreatywności z najnowszymi technologiami AI, aby dostarczać niespotykane rezultaty."
      />
      <div className="max-w-7xl mx-auto">
        {/* Header Section */}
        <div className="mb-24 md:mb-32">
          <h1 className="text-sm md:text-base tracking-[0.3em] uppercase text-white/50 font-bold mb-8">
            {t('Wizja LUŹNO', 'LUŹNO Vision')}
          </h1>
          <h2 className="text-3xl md:text-5xl lg:text-6xl font-light tracking-tight max-w-5xl leading-[1.2]">
            {t('W świecie, w którym pytania i odpowiedzi są masowo generowane przez algorytmy, kluczową walutą staje się ', 'In a world where questions and answers are massively generated by algorithms, the key currency becomes ')}<span className="font-bold italic">{t('zrozumienie ludzkich motywacji', 'understanding human motivations')}</span>.
          </h2>
          <p className="mt-8 text-lg md:text-xl text-white/60 max-w-3xl font-light leading-relaxed">
            {t('Żyjemy w czasach ekstremalnej dynamiki – wiedza techniczna dezaktualizuje się szybko, a presja na automatyzację często przesłania cel komunikacji.', 'We live in times of extreme dynamics - technical knowledge becomes outdated quickly, and the pressure for automation often obscures the purpose of communication.')}
          </p>
          <p className="mt-4 text-lg md:text-xl text-white/80 max-w-3xl font-medium leading-relaxed">
            {t('Luźno to agencja digital i social media, która łączy kreatywność z automatyzacją AI, dostarczając najlepsze kampanie na polskim rynku.', 'Luźno is a digital and social media agency that combines creativity with AI automation, delivering the best campaigns on the market.')}
          </p>
        </div>

        {/* Split Layout Section */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-16 lg:gap-24 items-start relative">
          
          {/* Sticky Image Side */}
          <div className="lg:col-span-5 lg:sticky lg:top-32 h-[50vh] lg:h-[70vh] w-full relative flex items-center justify-center">
            <motion.div style={{ opacity }} className="absolute inset-0 w-full h-full">
              <div 
                className="absolute inset-0 w-full h-full mix-blend-luminosity opacity-70"
                style={{
                  maskImage: 'radial-gradient(ellipse at center, black 20%, transparent 70%)',
                  WebkitMaskImage: 'radial-gradient(ellipse at center, black 20%, transparent 70%)'
                }}
              >
                {/* Image: Visionary nature landscape, person looking at vast mountains */}
                <img 
                  src="https://images.unsplash.com/photo-1469474968028-56623f02e42e?q=80&w=2074&auto=format&fit=crop" 
                  alt="Wizja - natura i perspektywa" 
                  className="w-full h-full object-cover grayscale"
                  referrerPolicy="no-referrer"
                />
              </div>
            </motion.div>
            
            {/* Subtle overlay to enhance the "cool/professional" tone */}
            <div className="absolute inset-0 bg-blue-900/5 mix-blend-overlay pointer-events-none rounded-full blur-3xl" />
          </div>

          {/* Scrolling Text Side */}
          <motion.div 
            style={{ y }} 
            className="lg:col-span-6 lg:col-start-7 flex flex-col gap-24 pt-12 lg:pt-24 pb-24"
          >
            
            {/* Block 1 */}
            <div className="flex flex-col gap-6">
              <h3 className="text-2xl md:text-3xl font-bold tracking-tight">
                {t('W LUŻNO wierzymy, że wiedza i życiowa mądrość idą w parze z sukcesem.', 'At LUŹNO, we believe that knowledge and life wisdom go hand in hand with success.')}
              </h3>
              <div className="w-12 h-[1px] bg-white/30" />
              <p className="text-lg text-white/70 font-light leading-relaxed">
                {t('Niezależnie od zaawansowania technologii, w centrum naszych działań zawsze stawiamy odbiorcę. Analizujemy jego problemy, mapujemy marzenia i rozumiemy kontekst, w którym się znajduje. Narzędzia są dla nas wsparciem, a nie kompasem.', 'Regardless of technological advancement, we always put the recipient at the center of our activities. We analyze their problems, map their dreams and understand the context in which they find themselves. Tools are a support for us, not a compass.')}
              </p>
            </div>

            {/* Block 2 */}
            <div className="flex flex-col gap-6">
              <h3 className="text-2xl md:text-3xl font-bold tracking-tight">
                {t('Odporni na zmianę.', 'Resistant to change.')}
              </h3>
              <div className="w-12 h-[1px] bg-white/30" />
              <p className="text-lg text-white/70 font-light leading-relaxed">
                {t('Skillset, który budujemy sprawia, że jesteśmy nie tylko odporni na zmianę technologiczną, ale wyprzedzamy konkurencję dzięki pierwiastkowi ludzkiemu, który kultywujemy. Niech zasada ', 'The skillset we build makes us not only resistant to technological change, but we stay ahead of the competition thanks to the human element we cultivate. Let the principle ')}<span className="text-white italic font-medium">„You get what you ask for”</span> {t('pozostanie nam wszystkim w głowach.', 'remain in all our minds.')}
              </p>
              <p className="text-lg text-white/70 font-light leading-relaxed">
                {t('Ci działający bez odpowiednio silnych fundamentów, bez wiedzy na temat strategii, czy komunikacji będą tylko twórcami generycznych promptów w fake\'owym świecie.', 'Those operating without sufficiently strong foundations, without knowledge of strategy or communication will only be creators of generic prompts in a fake world.')}
              </p>
            </div>

            {/* Block 3 */}
            <div className="flex flex-col gap-6">
              <h3 className="text-2xl md:text-3xl font-bold tracking-tight">
                {t('Przyszłość to bliskość i dialog.', 'The future is closeness and dialogue.')}
              </h3>
              <div className="w-12 h-[1px] bg-white/30" />
              <p className="text-lg text-white/70 font-light leading-relaxed">
                {t('Dla nas technologia to tylko kanał. Prawdziwa wartość drzemie w umiejętności prowadzenia rozmowy, która wywołuje realną reakcję i buduje trwałe więzi. Bez względu na formę, zawsze wybieramy jakość relacji ponad masowość przekazu.', 'For us, technology is just a channel. True value lies in the ability to conduct a conversation that provokes a real reaction and builds lasting bonds. Regardless of the form, we always choose the quality of relationships over mass messaging.')}
              </p>
            </div>

          </motion.div>
        </div>
      </div>
    </motion.main>
  );
}
